-- MySQL Script generated by MySQL Workbench
-- Wed Jul 16 20:41:13 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cardapio_digital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cardapio_digital` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cardapio_digital` ;

-- -----------------------------------------------------
-- Table `cardapio_digital`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_digital`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`mesa` (
  `id` INT NOT NULL,
  `num` VARCHAR(45) NOT NULL,
  `ativa` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_digital`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` TEXT NOT NULL,
  `preco` FLOAT NOT NULL,
  `imagem` VARCHAR(200) NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_categoria1_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_item_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `cardapio_digital`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_digital`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`token` (
  `cod` VARCHAR(6) NOT NULL,
  `ativado_em` DATETIME NULL,
  `mesa_id` INT NOT NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_token_mesa1_idx` (`mesa_id` ASC),
  CONSTRAINT `fk_token_mesa1`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `cardapio_digital`.`mesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_digital`.`item_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`item_estoque` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_estoque_item_idx` (`item_id` ASC),
  CONSTRAINT `fk_item_estoque_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `cardapio_digital`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_digital`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`feedback` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `avaliacao` DECIMAL(10,0) NOT NULL,
  `comentario` TEXT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_feedback_item1_idx` (`item_id` ASC),
  CONSTRAINT `fk_feedback_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `cardapio_digital`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_digital`.`cupon_desconto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`cupon_desconto` (
  `cod` VARCHAR(45) NOT NULL,
  `valor_desconto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_digital`.`cliente_fidelizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`cliente_fidelizado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL COMMENT '	',
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `ultimo_login` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_digital`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`conta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  `token_cod` VARCHAR(6) NOT NULL,
  `cupon_desconto_cod` VARCHAR(45) NULL,
  `cliente_fidelizado_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_conta_token1_idx` (`token_cod` ASC),
  INDEX `fk_conta_cupon_desconto1_idx` (`cupon_desconto_cod` ASC),
  INDEX `fk_conta_cliente_fidelizado1_idx` (`cliente_fidelizado_id` ASC),
  CONSTRAINT `fk_conta_token1`
    FOREIGN KEY (`token_cod`)
    REFERENCES `cardapio_digital`.`token` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_cupon_desconto1`
    FOREIGN KEY (`cupon_desconto_cod`)
    REFERENCES `cardapio_digital`.`cupon_desconto` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_cliente_fidelizado1`
    FOREIGN KEY (`cliente_fidelizado_id`)
    REFERENCES `cardapio_digital`.`cliente_fidelizado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_digital`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_criacao` DATETIME NOT NULL,
  `status` INT NOT NULL,
  `conta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_conta1_idx` (`conta_id` ASC),
  CONSTRAINT `fk_pedido_conta1`
    FOREIGN KEY (`conta_id`)
    REFERENCES `cardapio_digital`.`conta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_digital`.`item_estoque_has_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`item_estoque_has_pedido` (
  `item_estoque_id` INT NOT NULL,
  `pedido_id` INT NOT NULL,
  PRIMARY KEY (`item_estoque_id`, `pedido_id`),
  INDEX `fk_item_estoque_has_pedido_pedido1_idx` (`pedido_id` ASC),
  INDEX `fk_item_estoque_has_pedido_item_estoque1_idx` (`item_estoque_id` ASC),
  CONSTRAINT `fk_item_estoque_has_pedido_item_estoque1`
    FOREIGN KEY (`item_estoque_id`)
    REFERENCES `cardapio_digital`.`item_estoque` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_estoque_has_pedido_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `cardapio_digital`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_digital`.`chamada_garcom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`chamada_garcom` (
  `id` INT NOT NULL,
  `status` INT NOT NULL,
  `token_cod` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chamada_garcom_token1_idx` (`token_cod` ASC),
  CONSTRAINT `fk_chamada_garcom_token1`
    FOREIGN KEY (`token_cod`)
    REFERENCES `cardapio_digital`.`token` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_digital`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`administrador` (
  `id` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `cod_funcionario` VARCHAR(45) NOT NULL,
  `ultimo_login` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
