-- MySQL Script generated by MySQL Workbench
-- Wed 09 Jul 2014 11:37:52 PM BRT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cardapio_digital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cardapio_digital` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cardapio_digital` ;

-- -----------------------------------------------------
-- Table `cardapio_digital`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_digital`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`mesa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_digital`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` TEXT NOT NULL,
  `preco` FLOAT NOT NULL,
  `imagem` VARCHAR(200) NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_categoria1_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_item_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `cardapio_digital`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_digital`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`token` (
  `cod` VARCHAR(6) NOT NULL,
  `ativado_em` DATETIME NULL,
  `mesa_id` INT NOT NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_token_mesa1_idx` (`mesa_id` ASC),
  CONSTRAINT `fk_token_mesa1`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `cardapio_digital`.`mesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapio_digital`.`item_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapio_digital`.`item_estoque` (
  `id` INT NOT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_estoque_item_idx` (`item_id` ASC),
  CONSTRAINT `fk_item_estoque_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `cardapio_digital`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
